openapi: 3.1.0
info:
  version: 0.0.1
  title: 輪廻サークル
  description: 輪廻サークル用API

  contact:
    name: hibohiboo
    url: https://hibohiboo.github.io/RinneCircle/ja/introduction/

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT


paths:
  /v1/api/scenario:
    $ref: paths/rinne.yml


components:
  securitySchemes:
    ApiKeyAuth:
      $ref: components/schemas/apiKey.yml

