spectaql:
  logoFile: ./favicon.svg
  faviconFile: ./favicon.svg
  displayAllServers: true

introspection:
  removeTrailingPeriodFromDescriptions: false
  schemaFile: ./data/schema.gql
  metadataFile: ./data/metadata.json
  dynamicExamplesProcessingModule: ./customizations/examples
  queryNameStrategy: capitalizeFirst
  fieldExpansionDepth: 2

  spectaqlDirective:
    enable: true

extensions:
  graphqlScalarExamples: true

info:
  title: RinneCircle GraphQL API Reference
  description: 輪廻サークル データベース
  # termsOfService: https://hibohiboo.github.io/RinneCircle/ja/introduction/
  contact:
    name: API Support
    url: https://twitter.com/hibohiboo

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html


servers:
  - url: https://valid-snail-97.hasura.app/v1/graphql
    description: Hasura
